# Generated by Django 6.0.2 on 2026-02-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='variables',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
