# Generated by Django 5.2.11 on 2026-02-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_id_alter_campaigncontact_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_number',
            field=models.CharField(default='+19198041653', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaigncontact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
