# Generated by Django 5.2.11 on 2026-02-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_campaign_options_campaign_actual_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_number',
            field=models.CharField(blank=True, default='+19198041653', max_length=20, null=True),
        ),
    ]
