# Generated by Django 5.2.11 on 2026-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_campaign_from_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontact',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
