// Void Bastion Defense - Steam Preload Script
// This file is generated by electron-wrapper.ts
// Injected into the renderer process to expose Steam API

const { contextBridge, ipcRenderer } = require('electron');

// Steam API for renderer process
contextBridge.exposeInMainWorld('steamAPI', {
  // Achievements
  unlockAchievement: (achievementId) => ipcRenderer.invoke('steam:unlockAchievement', achievementId),
  getAchievements: () => ipcRenderer.invoke('steam:getAchievements'),

  // Rich Presence
  setRichPresence: (status, details) => ipcRenderer.invoke('steam:setRichPresence', status, details),
  startGamePresence: (wave, score) => ipcRenderer.invoke('steam:startGamePresence', wave, score),
  stopGamePresence: () => ipcRenderer.invoke('steam:stopGamePresence'),

  // Stats
  getPlayerStats: () => ipcRenderer.invoke('steam:getPlayerStats'),
  updateStat: (statName, value) => ipcRenderer.invoke('steam:updateStat', statName, value),

  // Leaderboards
  getLeaderboard: (leaderboardName, type, start, end) => 
    ipcRenderer.invoke('steam:getLeaderboard', leaderboardName, type, start, end),
  uploadScore: (leaderboardName, score, details) => 
    ipcRenderer.invoke('steam:uploadScore', leaderboardName, score, details),
  getWeeklyChallenge: () => ipcRenderer.invoke('steam:getWeeklyChallenge'),

  // Cloud Saves
  saveGame: (data) => ipcRenderer.invoke('steam:saveGame', data),
  loadGame: () => ipcRenderer.invoke('steam:loadGame'),
  syncSaves: () => ipcRenderer.invoke('steam:syncSaves'),
  getSaveSummary: () => ipcRenderer.invoke('steam:getSaveSummary'),

  // Steam Info
  getSteamId: () => ipcRenderer.invoke('steam:getSteamId'),
  getUserName: () => ipcRenderer.invoke('steam:getUserName'),
  isSteamRunning: () => ipcRenderer.invoke('steam:isRunning'),

  // Overlay
  activateOverlay: (option) => ipcRenderer.invoke('steam:activateOverlay', option),
});

console.log('[Preload] Steam API exposed');
