# Generated by Django 5.2.11 on 2026-02-19 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(max_length=100, unique=True)),
                ('from_phone', models.CharField(max_length=20)),
                ('to_phone', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['to_phone', 'seen'], name='sms_notific_to_phon_1d9460_idx'), models.Index(fields=['timestamp'], name='sms_notific_timesta_0fc5eb_idx')],
            },
        ),
    ]
